kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: my-kind
networking:
    apiServerAddress: "127.0.0.1"
    apiServerPort: 6443
    podSubnet: "172.16.0.1/16"
    serviceSubnet: "172.17.0.1/16"

nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP

  extraMounts:
  - hostPath: /home/kali/docker/kind/data/
    containerPath: /data
    # optional: if set, the mount is read-only.
    # default false
    readOnly: false
    # optional: if set, the mount needs SELinux relabeling.
    # default false
    selinuxRelabel: false
    # optional: set propagation mode (None, HostToContainer or Bidirectional)
    # see https://kubernetes.io/docs/concepts/storage/volumes/#mount-propagation
    # default None
    propagation: HostToContainer
